services:
  - type: web
    name: backend
    env: python
    buildCommand: pip install -r server/requirements.txt
    startCommand: python server/app.py
    rootDirectory: ./server

  - type: static
    name: frontend
    env: static
    buildCommand: npm install && npm run build
    publishDirectory: client/build
    rootDirectory: ./client
